### ISSUE TITLE
Bot difficulty (optional)

### ISSUE THREAD

**Issue by schmetris** [A-Level-Personal-Code-Collab/PirateGame#175]
Add an optional difficulty for bots. This will affect what items are in the bots' grid, and (possibly) who they target.
E.g. hardcore bots would have no bomb, more 5000s, more banks, more mirrors/shields, more actions and would always target the winning player.
An easy bot would have less/no defensive items, one bank, and less actions.

**Comment by Lime-Parallelogram** [comment]
Bots currently too far down the line, closing for now
