### ISSUE TITLE
Join Game EOU 🚪

### ISSUE THREAD

**Issue by Theocat321** [A-Level-Personal-Code-Collab/PirateGame#21]
Make the join game window easier for an end-user in the following ways
- [x] Add little info dot next to username input box explaining that for filtering and moderation reasons only letters are allowed and some nicknames may be rejected by the server due to the inclusion of blacklisted strings
- [x] Add info next to game ID box explaining that this is an 8 digit numerical code provided by game host

**Comment by Theocat321** [comment]
Currently cant find a way to do this effectivly

**Comment by Lime-Parallelogram** [comment]
Possible you could make some sort of fancy tooltip when you hover over the text. (https://www.w3schools.com/howto/howto_css_tooltip.asp). If we wanted a dedicated icon you could have a separate span tag containing an 🛈 icon.

**Comment by Theocat321** [comment]
Great idea, i will give that a go!

**Comment by Theocat321** [comment]
Just realised this isnt the task i thought it was, i will do this soon
